### ISSUE TITLE
INSTALL-file

### ISSUE THREAD

**Issue by Daijobou** [tessus/apachetop#2] opened 2015-12-23 15:14 UTC
Not everybody use automake 1.13. I use centos and latest version 1.11 can't compile this files. You need to re-create files for compiling with:

```
aclocal
automake
./configure
make
```

Maybe add this as hint in INSTALL-file? ;)

**Comment by tessus** [comment] 2015-12-23 17:05
Are you saying that `./configure` doesn't work on your system without recreating it with autotools 1.11?

If so, can you please post the error message here?

**Comment by Daijobou** [comment] 2015-12-23 17:29
The error was:

```
automake-1.13: command not found
WARNING: 'automake-1.13' is missing on your system.
```

but automake is installed on centOS 6.x:
Package automake-1.11.1-4.el6.noarch already installed and latest version

**Comment by tessus** [comment] 2015-12-23 17:47
You don't need automake to run `./configure`.
You only need the autotools to create configure and the other files from scratch (using the .ac and .am files). 

Can you please be a bit more specific in your problem description? You sent me the error message, but which command caused it?
What did you do? What was the error message?

You extract the .tar.gz and run `./configure` and then `make` to compile apachetop. You don't need autotools. You only need autotools, if you change the .ac and .am files.

**Comment by tessus** [comment] 2015-12-28 23:25
Due to no further feedback I'll close this issue.

I still do not know what you actually try to do. Next time, please include a detailed problem description and how to reproduce it. Thanks.

**Closed as completed by tessus** 2015-12-28 23:25 UTC
Labels: invalid, feedback
