### ISSUE TITLE
key-based commands don't respond immediately / workaround

### ISSUE THREAD

**Issue by carehart** [tessus/apachetop#17] opened 2023-08-05 19:23 UTC
Chris, thanks so much for the tool (which I re-discovered only yesterday, after first seeing it in 2015 then losing track of it--my loss).

But as I was exploring it, I am finding that the key-based commands (q for quit, p for pause, h for help, or the more powerful d, s, and others) are not responding immediately. Indeed, at first I thought they were not responding at all.

Then I realized what's happening (for me, at least): **the commands are only processed when a new Apache/httpd request is run** (and thus logged, thus triggering your tool to detect that I suppose).   Does that make sense to you?  Has anyone else experienced it? I happened to be testing it in a dev box where I had only occasional requests I was running.

And I really do mean, for instance, that if I opened the tool and it displayed its lines of output, if I hit q it would not even quit. (I'd have to use ctrl-c.) And all other key-based commands also would just not respond. I only discovered what I did by accident, when I had hit the q, switched away to run a request to see its impact on the UI, and then came back and found it HAD quit. Then I proved this was the case with all other keys, like h and p, etc.

If it helps to hear, this is on Apache/2.4.41, running on Ubuntu 20.04.6. (And if it may matter, I do happen to be running that within a WSL-based container.)

If you may confirm it happens on whatever platform you run, I suppose it could be that you/others maybe only ever had it running against an Apache that was more active. :-)  But since some may well test it on such a local/dev env first, I'd think others must have experienced it, but I don't see it discussed in closed issues.

Again, I really appreciate your effort with the tool, and I apologize in advance if somehow you/we discover that this is some unique environmental matter on my end. I was tempted to take the time to create a real vm (without WSL), and perhaps with a later Ubuntu or other distro. But I thought I may as well take my chances and offer this here, again if it may help someone else (even if they may find it as a closed issue that could not be reproduced by anyone else.)

**Comment by tessus** [comment] 2023-08-05 20:01
Hi Charlie. Thanks for reporting this issue.

I am not Chris Elsworth, who wrote apachetop. I asked Chris many years ago (I think almost a decade ago) what the status was and whether he had any problems with me maintaining it. We agreed on me maintaining it until he decides to work on it again. I haven't heard anything from him since then.

I just tried to replicate your issue, but wasn't able to reproduce it. I compiled the latest release on Fedora 38 and on macOS just now and pointed it to an empty file and then also to a valid access_log.
In both cases I can quit apachetop when pressing `q`. The other keys also work immediately.

I believe that apachetop was ahead of its time when it was developed by Chris almost 20 years ago. But these days it rather seems dated and there are other tools like goaccess that not only have a text interface but also allow to stream the data to a web server.
As sad as it is this project is pretty much dead. I don't have any stats on how many people are using it, but with other tools available, I highly doubt that there are many.

**Comment by carehart** [comment] 2023-08-05 21:16
Thanks so much, Helmut. Sorry, I didn't even look up who was behind the Tessus repo. I was just going on the readme and man page. I totally understand how such transitions go, and bless you for taking up the flag! :-)  And I understand your sentiments, and again thanks for sharing them (so people can know where things stand).

And thanks especially for confirming that you could not recreate the situation. I will try to find time to try variants to discover where this problem comes in, whether in the version of Apache, or of Ubuntu, or of running within WSL (the latter may seem an obvious choice to some, but it is a real linux kernel rather than some emulator like cygwin, etc).

In any case, as for your observation about goaccess, well, I can understand why many might like it (and people have long loved general web server log analysis tools), but it doesn't offer this unique focus of apachetop on just the most recent time or traffic (I couldn't find a way to get it to do that, so I could be mistaken).

As such--and because apachetop still comes up when people search for tools to help with understanding "current" processing, I suspect people continue using it for a long time. Again I do understand that folks who run such things may not want to stick around for that "long tail" to dwindle. :-)

FWIW, my real hope was to find something that would show what IS running (not just what was slow recently), and of course apachetop (or any log-based tool) won't be able to help with that, as they will blind to running requests until apache logs them when they complete). And yes, I'm aware of mod_status (and its W state), and of grepping for that, or awking it to simplify its output. (I leave that  breadcrumb for others.) 

Again, I just came across apachetop while in my explorations, and found it nice and only challenged for me in this one point of the keys. It may well fall off my radar, but the beauty of github is that someone may find this and ping me about it, and perhaps I may have new info or renewed vigor to resolve that.

Hope you can maintain yours. I really appreciate the kind response, and your efforts.

**Comment by tessus** [comment] 2023-08-06 02:21
You are welcome and also thank you for your kind words.

I'll close this issue for now. Please let me know, if I should activate discussions for this repo and convert this issue to a discussion. I am still not entirely sure what and how people search on github. e.g. I also search closed issues, but others do not. However, even with discussions a closed discussion does not show up either.

**Closed as completed by tessus** 2023-08-06 02:21 UTC
